.\" Man page for Ukui-Panel
.TH DISKATATUSICON 1 "20 September 2018" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
diskstatusicon \- The tool for the UKUI Desktop Environment
.SH "SYNOPSIS"
.B diskstatusicon 
.SH "DESCRIPTION"
The \fBdiskstatusicon\fR program is a part of the ukui-indicators, It provides disk manager for the the UKUI Desktop Environment. Detect the system disk automatically, Can pop up and open the device.
.PP
This manual page documents the \fBdiskstatusicon\fR command.
.P
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui-desktop/ukui-indicators/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
quankang <quankang@kylinos.cn> (2018)
.SH "SEE ALSO"
